remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Demo of IAFF-VC
description: Kai Guo<sup>a,b</sup>, Yang Xu<sup>a,b,∗</sup>, and Sicong Zhang<sup>a,b</sup> <br>
<sup>a</sup>School of Cyber Science and Technology, Guizhou Normal University, Guiyang 550001, China <br>
<sup>b</sup>Key Laboratory of Information and computing Science Guizhou Province, Guizhou Normal University, Guiyang 550001, China
